# Project: ʵѵ
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Dijkstra.o File.o main.o Management.o Menu.o OutPut.o Queue.o Search.o SqList.o Statistics.o
LINKOBJ  = Dijkstra.o File.o main.o Management.o Menu.o OutPut.o Queue.o Search.o SqList.o Statistics.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ʵѵ.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Dijkstra.o: Dijkstra.cpp
	$(CPP) -c Dijkstra.cpp -o Dijkstra.o $(CXXFLAGS)

File.o: File.cpp
	$(CPP) -c File.cpp -o File.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Management.o: Management.cpp
	$(CPP) -c Management.cpp -o Management.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)

OutPut.o: OutPut.cpp
	$(CPP) -c OutPut.cpp -o OutPut.o $(CXXFLAGS)

Queue.o: Queue.cpp
	$(CPP) -c Queue.cpp -o Queue.o $(CXXFLAGS)

Search.o: Search.cpp
	$(CPP) -c Search.cpp -o Search.o $(CXXFLAGS)

SqList.o: SqList.cpp
	$(CPP) -c SqList.cpp -o SqList.o $(CXXFLAGS)

Statistics.o: Statistics.cpp
	$(CPP) -c Statistics.cpp -o Statistics.o $(CXXFLAGS)
